### ISSUE TITLE
test owl2bench fails trying to abstract the ABox. NullPointerException

### ISSUE THREAD

**Issue by iamcrowd** [iamcrowd/t-crowd-lib#9]
java.lang.NullPointerException
	at it.unibz.inf.tdllitefpx.abox.ABox.addExtensionConstraintsAbsABox(ABox.java:606)
	at it.unibz.inf.dllite.DLLiteReasoner.checkKB(DLLiteReasoner.java:160)
	at it.gilia.tcrowd.cli.dllite.TCrowdSatisfiabilityChecking.run(TCrowdSatisfiabilityChecking.java:47)
	at it.gilia.tcrowd.cli.TCrowd.main(TCrowd.java:20)

**Comment by gnatenko** [comment]
Fixed
